from trading_platform import TradingPlatform

class Backtester_Portfolio(TradingPlatform):
    
    def __init__(self) -> None:
        ...    
    def connect():
        ...
    def terminate_connection():
        ...
    def get_portfolio():
        ...
    def get_min_order():
        ...
    def place_market_order():
        ...
